Complaint Rejected and resolved pages added
egovernments/egov-qa pull request #4
Opened 2018-03-26 06:55 UTC by ramakrishnaippili

2018-03-27 04:20 UTC, tarunlalwani requested changes
Please check the 2 pages for additional actions

2018-03-27 04:20 UTC, tarunlalwani commented on pages/ComplaintRejected.py
> +class _ComplaintRejected(Page):
There are no actions on a complain rejected page?

2018-03-27 04:20 UTC, tarunlalwani commented on pages/ComplaintResolved.py
> +    def navigate(self):
No Action here also?

2018-03-28 05:07 UTC, ramakrishnaippili commented on pages/ComplaintRejected.py
> +class _ComplaintRejected(Page):
Added reopen button with class identifier...

2018-04-03 09:46 UTC, ramakrishnaippili commented
closing this as the structure of project changed... these changed will be added manually.

2018-04-03 09:46 UTC, closed without merging