Added Pages for Login, Reopen Complaint, and Complaint Status Filed
egovernments/egov-qa pull request #6
Opened 2018-03-26 07:12 UTC by ManjueGov

Changes updated after first review and requesting pull.

2018-03-27 04:12 UTC, tarunlalwani requested changes
Please fix the issues

2018-03-27 04:12 UTC, tarunlalwani commented on pages/Profile.py
> +    def profileupdate(self, name, emailid):
the name should be `profile_update`

2018-03-27 04:12 UTC, tarunlalwani commented on pages/Profile.py
> +    def profilephotoremover(self):
name should be `profile_photo_remove`.

2018-03-27 04:12 UTC, tarunlalwani commented on pages/Profile.py
> +    def profilesave(self):
Remove `profile` from all these methods since we know we are using the `ProfilePage`

2018-03-27 04:12 UTC, tarunlalwani commented on tests/test_registration.py
> +from pages.ReopenComplaint import ReopenComplaintPage
Page should be import directly from `pages`

2018-03-27 04:12 UTC, tarunlalwani commented on tests/test_registration.py
> +from pages import OTPPage, AddComplaintPage, ComplaintTypePage, TopMenuPage, BottomMenuPage, ProfilePage
Import every page in new line so that conflicts can be resolved easily when merging

2018-03-27 04:12 UTC, tarunlalwani commented on tests/test_registration.py
> +    quit_driver()
`quit_driver` will not be part of the tests. I have added a new hook which will automatically quit the driver

2018-03-27 06:41 UTC, ManjueGov commented
Done changes according to review.

2018-03-28 04:54 UTC, tarunlalwani approved these changes
Reviewed and apprived

2018-03-28 04:57 UTC, merged

2018-03-28 05:18 UTC, ManjueGov commented
Thanks for the review @tarunlalwani